version: "3.9"
services:
  review_service_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: review_service_server
    restart: on-failure
    ports:
      - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/review_service
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      # - mysql
    networks:
      - ku-wongnai_ku-wongnai

volumes:
  db_data:

networks:
  ku-wongnai_ku-wongnai:
    external: true
