version: "3.9"
services:
  review_service_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: review_service_server
    restart: on-failure
    ports:
      - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql:3306/review_service}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME:-root}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD:-root}"
      RABBITMQ_HOST: "${RABBITMQ_HOST:-rabbitmq}"
      RABBITMQ_PORT: "${RABBITMQ_PORT:-5672}"
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME:-user}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD:-password}"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - ku-wongnai_ku-wongnai

volumes:
  db_data:

networks:
  ku-wongnai_ku-wongnai:
    external: true
